#!/usr/bin/env python3
"""
Script to add new proposals to vecstore.json with precomputed embeddings.
Run this locally (requires sentence-transformers).

Usage:
    python3 scripts/add-proposals.py
"""

import json
from pathlib import Path

# Only import if available (local dev only)
try:
    from sentence_transformers import SentenceTransformer
    model = SentenceTransformer('all-MiniLM-L6-v2')
    print("✅ sentence-transformers loaded")
except ImportError:
    print("❌ Please install: pip install sentence-transformers")
    exit(1)


def add_proposal(doc_id: str, text: str, dao: str, prop_type: str = "proposal"):
    """
    Add a new proposal to vecstore.json with precomputed embedding.
    
    Args:
        doc_id: Unique identifier (e.g. "uniswap-prop-006")
        text: Full proposal text
        dao: DAO name (e.g. "uniswap", "1inch", "arbitrum")
        prop_type: Type ("proposal", "governance-doc", "voting-guide")
    """
    vecstore_path = Path(__file__).parent.parent / "data" / "vecstore.json"
    
    # Load existing vecstore
    with open(vecstore_path, 'r') as f:
        data = json.load(f)
    
    # Check if doc_id already exists
    if doc_id in data:
        print(f"⚠️  {doc_id} already exists. Skipping...")
        return False
    
    # Generate embedding
    print(f"🧠 Generating embedding for {doc_id}...")
    embedding = model.encode(text).tolist()
    
    # Add to vecstore
    data[doc_id] = {
        "text": text,
        "embedding": embedding,
        "dao": dao,
        "type": prop_type
    }
    
    # Save back to file
    with open(vecstore_path, 'w') as f:
        json.dump(data, f, indent=2)
    
    print(f"✅ Added {doc_id} ({len(embedding)}D embedding)")
    return True


def main():
    """
    Add new proposals here.
    Fetch real proposal text from Snapshot, governance forums, etc.
    """
    
    # Example: Add Uniswap proposal 6
    uniswap_prop_6 = """
    # Uniswap Grants Program - Season 3
    
    ## Summary
    This proposal seeks to renew the Uniswap Grants Program for Season 3 with a budget of 1.5M UNI tokens.
    
    ## Background
    The Grants Program has successfully funded 45 projects in Season 2, including:
    - 15 developer tools
    - 12 community initiatives
    - 8 research projects
    - 10 educational programs
    
    ## Requested Budget
    - Total: 1,500,000 UNI (~$7.5M at current prices)
    - Grant sizes: 10K-100K UNI per project
    - Duration: 6 months (Jan-Jun 2024)
    
    ## Success Metrics
    - 50+ projects funded
    - 80% completion rate
    - $500K+ TVL generated by funded dApps
    
    ## Team
    - Program Manager: Alice (3 years DAO experience)
    - Review Committee: 7 delegates with avg 100K+ UNI voting power
    """
    
    # Example: Add 1inch proposal
    oneinch_prop_7 = """
    # 1inch Network Liquidity Mining Program V2
    
    ## Abstract
    Extend the liquidity mining program for 1inch liquidity pools with enhanced incentives.
    
    ## Motivation
    Current liquidity is concentrated in top 3 pools. This proposal expands to 10 pools.
    
    ## Specification
    - Budget: 10M 1INCH tokens ($5M)
    - Duration: 3 months
    - Target pools: ETH/USDC, ETH/USDT, DAI/USDC, WBTC/ETH, and 6 others
    - Emissions: 111K 1INCH per day distributed pro-rata by TVL
    
    ## Risk Assessment
    - Smart contract risk: Audited by OpenZeppelin
    - Economic risk: May dilute token holders
    - Opportunity cost: Compared to treasury staking (3% APY)
    
    ## Voting Options
    - For: Approve 10M 1INCH allocation
    - Against: Reject proposal
    - Abstain: No preference
    """
    
    # Add proposals
    proposals_added = 0
    
    if add_proposal(
        doc_id="uniswap-prop-006",
        text=uniswap_prop_6,
        dao="uniswap",
        prop_type="proposal"
    ):
        proposals_added += 1
    
    if add_proposal(
        doc_id="1inch-prop-007",
        text=oneinch_prop_7,
        dao="1inch",
        prop_type="proposal"
    ):
        proposals_added += 1
    
    print()
    print(f"🎉 Successfully added {proposals_added} new proposals!")
    print("📤 Next steps:")
    print("   1. Review data/vecstore.json")
    print("   2. Test locally: npm run dev")
    print("   3. Push to GitHub: git add . && git commit -m 'Add proposals' && git push")
    print("   4. Render will auto-deploy with new embeddings")


if __name__ == "__main__":
    main()
